// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace StreamingFormat {
class InitDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Init> {
} _Init_default_instance_;
class DefaultPosDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<DefaultPos> {
} _DefaultPos_default_instance_;
class CameraDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Camera> {
} _Camera_default_instance_;
class ImageDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Image> {
} _Image_default_instance_;
class EndingDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Ending> {
} _Ending_default_instance_;
class StreamingMessageDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<StreamingMessage> {
} _StreamingMessage_default_instance_;

namespace protobuf_message_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[6];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Init, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Init, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Init, hight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Init, moduleid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultPos, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultPos, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultPos, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultPos, z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultPos, vx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultPos, vy_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultPos, vz_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, serialnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, delta_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, delta_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, delta_z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, delta_vx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, delta_vy_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, delta_vz_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Image, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Image, serialnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Image, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Image, size_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Ending, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamingMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamingMessage, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamingMessage, initmsg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamingMessage, defaultposmsg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamingMessage, cameramsg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamingMessage, imagemsg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StreamingMessage, endingmsg_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Init)},
  { 7, -1, sizeof(DefaultPos)},
  { 17, -1, sizeof(Camera)},
  { 28, -1, sizeof(Image)},
  { 35, -1, sizeof(Ending)},
  { 39, -1, sizeof(StreamingMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Init_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_DefaultPos_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Camera_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Image_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Ending_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_StreamingMessage_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "message.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

}  // namespace

void TableStruct::Shutdown() {
  _Init_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _DefaultPos_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _Camera_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _Image_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
  _Ending_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
  _StreamingMessage_default_instance_.Shutdown();
  delete file_level_metadata[5].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Init_default_instance_.DefaultConstruct();
  _DefaultPos_default_instance_.DefaultConstruct();
  _Camera_default_instance_.DefaultConstruct();
  _Image_default_instance_.DefaultConstruct();
  _Ending_default_instance_.DefaultConstruct();
  _StreamingMessage_default_instance_.DefaultConstruct();
  _StreamingMessage_default_instance_.get_mutable()->initmsg_ = const_cast< ::StreamingFormat::Init*>(
      ::StreamingFormat::Init::internal_default_instance());
  _StreamingMessage_default_instance_.get_mutable()->defaultposmsg_ = const_cast< ::StreamingFormat::DefaultPos*>(
      ::StreamingFormat::DefaultPos::internal_default_instance());
  _StreamingMessage_default_instance_.get_mutable()->cameramsg_ = const_cast< ::StreamingFormat::Camera*>(
      ::StreamingFormat::Camera::internal_default_instance());
  _StreamingMessage_default_instance_.get_mutable()->imagemsg_ = const_cast< ::StreamingFormat::Image*>(
      ::StreamingFormat::Image::internal_default_instance());
  _StreamingMessage_default_instance_.get_mutable()->endingmsg_ = const_cast< ::StreamingFormat::Ending*>(
      ::StreamingFormat::Ending::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\rmessage.proto\022\017StreamingFormat\"6\n\004Init"
      "\022\r\n\005width\030\002 \001(\r\022\r\n\005hight\030\003 \001(\r\022\020\n\010module"
      "ID\030\004 \001(\r\"Q\n\nDefaultPos\022\t\n\001x\030\002 \001(\r\022\t\n\001y\030\003"
      " \001(\r\022\t\n\001z\030\004 \001(\r\022\n\n\002vx\030\005 \001(\r\022\n\n\002vy\030\006 \001(\r\022"
      "\n\n\002vz\030\007 \001(\r\"\207\001\n\006Camera\022\024\n\014serialNumber\030\002"
      " \001(\r\022\017\n\007delta_x\030\003 \001(\r\022\017\n\007delta_y\030\004 \001(\r\022\017"
      "\n\007delta_z\030\005 \001(\r\022\020\n\010delta_vx\030\006 \001(\r\022\020\n\010del"
      "ta_vy\030\007 \001(\r\022\020\n\010delta_vz\030\010 \001(\r\";\n\005Image\022\024"
      "\n\014serialNumber\030\002 \001(\r\022\016\n\006status\030\003 \001(\r\022\014\n\004"
      "size\030\004 \001(\r\"\010\n\006Ending\"\234\002\n\020StreamingMessag"
      "e\022*\n\004type\030\001 \001(\0162\034.StreamingFormat.Messag"
      "eType\022&\n\007initMsg\030\002 \001(\0132\025.StreamingFormat"
      ".Init\0222\n\rdefaultPosMsg\030\003 \001(\0132\033.Streaming"
      "Format.DefaultPos\022*\n\tcameraMsg\030\004 \001(\0132\027.S"
      "treamingFormat.Camera\022(\n\010imageMsg\030\005 \001(\0132"
      "\026.StreamingFormat.Image\022*\n\tendingMsg\030\006 \001"
      "(\0132\027.StreamingFormat.Ending*]\n\013MessageTy"
      "pe\022\013\n\007MsgInit\020\000\022\021\n\rMsgDefaultPos\020\001\022\021\n\rMs"
      "gCameraInfo\020\002\022\014\n\010MsgImage\020\003\022\r\n\tMsgEnding"
      "\020\004b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 770);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_message_2eproto

const ::google::protobuf::EnumDescriptor* MessageType_descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_enum_descriptors[0];
}
bool MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Init::kWidthFieldNumber;
const int Init::kHightFieldNumber;
const int Init::kModuleIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Init::Init()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:StreamingFormat.Init)
}
Init::Init(const Init& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&width_, &from.width_,
    reinterpret_cast<char*>(&moduleid_) -
    reinterpret_cast<char*>(&width_) + sizeof(moduleid_));
  // @@protoc_insertion_point(copy_constructor:StreamingFormat.Init)
}

void Init::SharedCtor() {
  ::memset(&width_, 0, reinterpret_cast<char*>(&moduleid_) -
    reinterpret_cast<char*>(&width_) + sizeof(moduleid_));
  _cached_size_ = 0;
}

Init::~Init() {
  // @@protoc_insertion_point(destructor:StreamingFormat.Init)
  SharedDtor();
}

void Init::SharedDtor() {
}

void Init::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Init::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[0].descriptor;
}

const Init& Init::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

Init* Init::New(::google::protobuf::Arena* arena) const {
  Init* n = new Init;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Init::Clear() {
// @@protoc_insertion_point(message_clear_start:StreamingFormat.Init)
  ::memset(&width_, 0, reinterpret_cast<char*>(&moduleid_) -
    reinterpret_cast<char*>(&width_) + sizeof(moduleid_));
}

bool Init::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StreamingFormat.Init)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 width = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 hight = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &hight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 moduleID = 4;
      case 4: {
        if (tag == 32u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &moduleid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:StreamingFormat.Init)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StreamingFormat.Init)
  return false;
#undef DO_
}

void Init::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StreamingFormat.Init)
  // uint32 width = 2;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->width(), output);
  }

  // uint32 hight = 3;
  if (this->hight() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->hight(), output);
  }

  // uint32 moduleID = 4;
  if (this->moduleid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->moduleid(), output);
  }

  // @@protoc_insertion_point(serialize_end:StreamingFormat.Init)
}

::google::protobuf::uint8* Init::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:StreamingFormat.Init)
  // uint32 width = 2;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->width(), target);
  }

  // uint32 hight = 3;
  if (this->hight() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->hight(), target);
  }

  // uint32 moduleID = 4;
  if (this->moduleid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->moduleid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:StreamingFormat.Init)
  return target;
}

size_t Init::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StreamingFormat.Init)
  size_t total_size = 0;

  // uint32 width = 2;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width());
  }

  // uint32 hight = 3;
  if (this->hight() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->hight());
  }

  // uint32 moduleID = 4;
  if (this->moduleid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->moduleid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Init::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:StreamingFormat.Init)
  GOOGLE_DCHECK_NE(&from, this);
  const Init* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Init>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:StreamingFormat.Init)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:StreamingFormat.Init)
    MergeFrom(*source);
  }
}

void Init::MergeFrom(const Init& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:StreamingFormat.Init)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.hight() != 0) {
    set_hight(from.hight());
  }
  if (from.moduleid() != 0) {
    set_moduleid(from.moduleid());
  }
}

void Init::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:StreamingFormat.Init)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Init::CopyFrom(const Init& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StreamingFormat.Init)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Init::IsInitialized() const {
  return true;
}

void Init::Swap(Init* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Init::InternalSwap(Init* other) {
  std::swap(width_, other->width_);
  std::swap(hight_, other->hight_);
  std::swap(moduleid_, other->moduleid_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Init::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Init

// uint32 width = 2;
void Init::clear_width() {
  width_ = 0u;
}
::google::protobuf::uint32 Init::width() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Init.width)
  return width_;
}
void Init::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Init.width)
}

// uint32 hight = 3;
void Init::clear_hight() {
  hight_ = 0u;
}
::google::protobuf::uint32 Init::hight() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Init.hight)
  return hight_;
}
void Init::set_hight(::google::protobuf::uint32 value) {
  
  hight_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Init.hight)
}

// uint32 moduleID = 4;
void Init::clear_moduleid() {
  moduleid_ = 0u;
}
::google::protobuf::uint32 Init::moduleid() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Init.moduleID)
  return moduleid_;
}
void Init::set_moduleid(::google::protobuf::uint32 value) {
  
  moduleid_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Init.moduleID)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DefaultPos::kXFieldNumber;
const int DefaultPos::kYFieldNumber;
const int DefaultPos::kZFieldNumber;
const int DefaultPos::kVxFieldNumber;
const int DefaultPos::kVyFieldNumber;
const int DefaultPos::kVzFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DefaultPos::DefaultPos()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:StreamingFormat.DefaultPos)
}
DefaultPos::DefaultPos(const DefaultPos& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    reinterpret_cast<char*>(&vz_) -
    reinterpret_cast<char*>(&x_) + sizeof(vz_));
  // @@protoc_insertion_point(copy_constructor:StreamingFormat.DefaultPos)
}

void DefaultPos::SharedCtor() {
  ::memset(&x_, 0, reinterpret_cast<char*>(&vz_) -
    reinterpret_cast<char*>(&x_) + sizeof(vz_));
  _cached_size_ = 0;
}

DefaultPos::~DefaultPos() {
  // @@protoc_insertion_point(destructor:StreamingFormat.DefaultPos)
  SharedDtor();
}

void DefaultPos::SharedDtor() {
}

void DefaultPos::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DefaultPos::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[1].descriptor;
}

const DefaultPos& DefaultPos::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

DefaultPos* DefaultPos::New(::google::protobuf::Arena* arena) const {
  DefaultPos* n = new DefaultPos;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DefaultPos::Clear() {
// @@protoc_insertion_point(message_clear_start:StreamingFormat.DefaultPos)
  ::memset(&x_, 0, reinterpret_cast<char*>(&vz_) -
    reinterpret_cast<char*>(&x_) + sizeof(vz_));
}

bool DefaultPos::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StreamingFormat.DefaultPos)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 x = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 y = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 z = 4;
      case 4: {
        if (tag == 32u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 vx = 5;
      case 5: {
        if (tag == 40u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &vx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 vy = 6;
      case 6: {
        if (tag == 48u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &vy_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 vz = 7;
      case 7: {
        if (tag == 56u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &vz_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:StreamingFormat.DefaultPos)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StreamingFormat.DefaultPos)
  return false;
#undef DO_
}

void DefaultPos::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StreamingFormat.DefaultPos)
  // uint32 x = 2;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->x(), output);
  }

  // uint32 y = 3;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->y(), output);
  }

  // uint32 z = 4;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->z(), output);
  }

  // uint32 vx = 5;
  if (this->vx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->vx(), output);
  }

  // uint32 vy = 6;
  if (this->vy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->vy(), output);
  }

  // uint32 vz = 7;
  if (this->vz() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->vz(), output);
  }

  // @@protoc_insertion_point(serialize_end:StreamingFormat.DefaultPos)
}

::google::protobuf::uint8* DefaultPos::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:StreamingFormat.DefaultPos)
  // uint32 x = 2;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->x(), target);
  }

  // uint32 y = 3;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->y(), target);
  }

  // uint32 z = 4;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->z(), target);
  }

  // uint32 vx = 5;
  if (this->vx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->vx(), target);
  }

  // uint32 vy = 6;
  if (this->vy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->vy(), target);
  }

  // uint32 vz = 7;
  if (this->vz() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->vz(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:StreamingFormat.DefaultPos)
  return target;
}

size_t DefaultPos::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StreamingFormat.DefaultPos)
  size_t total_size = 0;

  // uint32 x = 2;
  if (this->x() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->x());
  }

  // uint32 y = 3;
  if (this->y() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->y());
  }

  // uint32 z = 4;
  if (this->z() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->z());
  }

  // uint32 vx = 5;
  if (this->vx() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->vx());
  }

  // uint32 vy = 6;
  if (this->vy() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->vy());
  }

  // uint32 vz = 7;
  if (this->vz() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->vz());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DefaultPos::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:StreamingFormat.DefaultPos)
  GOOGLE_DCHECK_NE(&from, this);
  const DefaultPos* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DefaultPos>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:StreamingFormat.DefaultPos)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:StreamingFormat.DefaultPos)
    MergeFrom(*source);
  }
}

void DefaultPos::MergeFrom(const DefaultPos& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:StreamingFormat.DefaultPos)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
  if (from.vx() != 0) {
    set_vx(from.vx());
  }
  if (from.vy() != 0) {
    set_vy(from.vy());
  }
  if (from.vz() != 0) {
    set_vz(from.vz());
  }
}

void DefaultPos::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:StreamingFormat.DefaultPos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DefaultPos::CopyFrom(const DefaultPos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StreamingFormat.DefaultPos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DefaultPos::IsInitialized() const {
  return true;
}

void DefaultPos::Swap(DefaultPos* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DefaultPos::InternalSwap(DefaultPos* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(z_, other->z_);
  std::swap(vx_, other->vx_);
  std::swap(vy_, other->vy_);
  std::swap(vz_, other->vz_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DefaultPos::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DefaultPos

// uint32 x = 2;
void DefaultPos::clear_x() {
  x_ = 0u;
}
::google::protobuf::uint32 DefaultPos::x() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.DefaultPos.x)
  return x_;
}
void DefaultPos::set_x(::google::protobuf::uint32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.DefaultPos.x)
}

// uint32 y = 3;
void DefaultPos::clear_y() {
  y_ = 0u;
}
::google::protobuf::uint32 DefaultPos::y() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.DefaultPos.y)
  return y_;
}
void DefaultPos::set_y(::google::protobuf::uint32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.DefaultPos.y)
}

// uint32 z = 4;
void DefaultPos::clear_z() {
  z_ = 0u;
}
::google::protobuf::uint32 DefaultPos::z() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.DefaultPos.z)
  return z_;
}
void DefaultPos::set_z(::google::protobuf::uint32 value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.DefaultPos.z)
}

// uint32 vx = 5;
void DefaultPos::clear_vx() {
  vx_ = 0u;
}
::google::protobuf::uint32 DefaultPos::vx() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.DefaultPos.vx)
  return vx_;
}
void DefaultPos::set_vx(::google::protobuf::uint32 value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.DefaultPos.vx)
}

// uint32 vy = 6;
void DefaultPos::clear_vy() {
  vy_ = 0u;
}
::google::protobuf::uint32 DefaultPos::vy() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.DefaultPos.vy)
  return vy_;
}
void DefaultPos::set_vy(::google::protobuf::uint32 value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.DefaultPos.vy)
}

// uint32 vz = 7;
void DefaultPos::clear_vz() {
  vz_ = 0u;
}
::google::protobuf::uint32 DefaultPos::vz() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.DefaultPos.vz)
  return vz_;
}
void DefaultPos::set_vz(::google::protobuf::uint32 value) {
  
  vz_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.DefaultPos.vz)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Camera::kSerialNumberFieldNumber;
const int Camera::kDeltaXFieldNumber;
const int Camera::kDeltaYFieldNumber;
const int Camera::kDeltaZFieldNumber;
const int Camera::kDeltaVxFieldNumber;
const int Camera::kDeltaVyFieldNumber;
const int Camera::kDeltaVzFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Camera::Camera()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:StreamingFormat.Camera)
}
Camera::Camera(const Camera& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&serialnumber_, &from.serialnumber_,
    reinterpret_cast<char*>(&delta_vz_) -
    reinterpret_cast<char*>(&serialnumber_) + sizeof(delta_vz_));
  // @@protoc_insertion_point(copy_constructor:StreamingFormat.Camera)
}

void Camera::SharedCtor() {
  ::memset(&serialnumber_, 0, reinterpret_cast<char*>(&delta_vz_) -
    reinterpret_cast<char*>(&serialnumber_) + sizeof(delta_vz_));
  _cached_size_ = 0;
}

Camera::~Camera() {
  // @@protoc_insertion_point(destructor:StreamingFormat.Camera)
  SharedDtor();
}

void Camera::SharedDtor() {
}

void Camera::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Camera::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[2].descriptor;
}

const Camera& Camera::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

Camera* Camera::New(::google::protobuf::Arena* arena) const {
  Camera* n = new Camera;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Camera::Clear() {
// @@protoc_insertion_point(message_clear_start:StreamingFormat.Camera)
  ::memset(&serialnumber_, 0, reinterpret_cast<char*>(&delta_vz_) -
    reinterpret_cast<char*>(&serialnumber_) + sizeof(delta_vz_));
}

bool Camera::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StreamingFormat.Camera)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 serialNumber = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &serialnumber_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 delta_x = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &delta_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 delta_y = 4;
      case 4: {
        if (tag == 32u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &delta_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 delta_z = 5;
      case 5: {
        if (tag == 40u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &delta_z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 delta_vx = 6;
      case 6: {
        if (tag == 48u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &delta_vx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 delta_vy = 7;
      case 7: {
        if (tag == 56u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &delta_vy_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 delta_vz = 8;
      case 8: {
        if (tag == 64u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &delta_vz_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:StreamingFormat.Camera)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StreamingFormat.Camera)
  return false;
#undef DO_
}

void Camera::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StreamingFormat.Camera)
  // uint32 serialNumber = 2;
  if (this->serialnumber() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->serialnumber(), output);
  }

  // uint32 delta_x = 3;
  if (this->delta_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->delta_x(), output);
  }

  // uint32 delta_y = 4;
  if (this->delta_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->delta_y(), output);
  }

  // uint32 delta_z = 5;
  if (this->delta_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->delta_z(), output);
  }

  // uint32 delta_vx = 6;
  if (this->delta_vx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->delta_vx(), output);
  }

  // uint32 delta_vy = 7;
  if (this->delta_vy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->delta_vy(), output);
  }

  // uint32 delta_vz = 8;
  if (this->delta_vz() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->delta_vz(), output);
  }

  // @@protoc_insertion_point(serialize_end:StreamingFormat.Camera)
}

::google::protobuf::uint8* Camera::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:StreamingFormat.Camera)
  // uint32 serialNumber = 2;
  if (this->serialnumber() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->serialnumber(), target);
  }

  // uint32 delta_x = 3;
  if (this->delta_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->delta_x(), target);
  }

  // uint32 delta_y = 4;
  if (this->delta_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->delta_y(), target);
  }

  // uint32 delta_z = 5;
  if (this->delta_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->delta_z(), target);
  }

  // uint32 delta_vx = 6;
  if (this->delta_vx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->delta_vx(), target);
  }

  // uint32 delta_vy = 7;
  if (this->delta_vy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->delta_vy(), target);
  }

  // uint32 delta_vz = 8;
  if (this->delta_vz() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->delta_vz(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:StreamingFormat.Camera)
  return target;
}

size_t Camera::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StreamingFormat.Camera)
  size_t total_size = 0;

  // uint32 serialNumber = 2;
  if (this->serialnumber() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->serialnumber());
  }

  // uint32 delta_x = 3;
  if (this->delta_x() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->delta_x());
  }

  // uint32 delta_y = 4;
  if (this->delta_y() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->delta_y());
  }

  // uint32 delta_z = 5;
  if (this->delta_z() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->delta_z());
  }

  // uint32 delta_vx = 6;
  if (this->delta_vx() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->delta_vx());
  }

  // uint32 delta_vy = 7;
  if (this->delta_vy() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->delta_vy());
  }

  // uint32 delta_vz = 8;
  if (this->delta_vz() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->delta_vz());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Camera::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:StreamingFormat.Camera)
  GOOGLE_DCHECK_NE(&from, this);
  const Camera* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Camera>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:StreamingFormat.Camera)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:StreamingFormat.Camera)
    MergeFrom(*source);
  }
}

void Camera::MergeFrom(const Camera& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:StreamingFormat.Camera)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.serialnumber() != 0) {
    set_serialnumber(from.serialnumber());
  }
  if (from.delta_x() != 0) {
    set_delta_x(from.delta_x());
  }
  if (from.delta_y() != 0) {
    set_delta_y(from.delta_y());
  }
  if (from.delta_z() != 0) {
    set_delta_z(from.delta_z());
  }
  if (from.delta_vx() != 0) {
    set_delta_vx(from.delta_vx());
  }
  if (from.delta_vy() != 0) {
    set_delta_vy(from.delta_vy());
  }
  if (from.delta_vz() != 0) {
    set_delta_vz(from.delta_vz());
  }
}

void Camera::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:StreamingFormat.Camera)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Camera::CopyFrom(const Camera& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StreamingFormat.Camera)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Camera::IsInitialized() const {
  return true;
}

void Camera::Swap(Camera* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Camera::InternalSwap(Camera* other) {
  std::swap(serialnumber_, other->serialnumber_);
  std::swap(delta_x_, other->delta_x_);
  std::swap(delta_y_, other->delta_y_);
  std::swap(delta_z_, other->delta_z_);
  std::swap(delta_vx_, other->delta_vx_);
  std::swap(delta_vy_, other->delta_vy_);
  std::swap(delta_vz_, other->delta_vz_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Camera::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Camera

// uint32 serialNumber = 2;
void Camera::clear_serialnumber() {
  serialnumber_ = 0u;
}
::google::protobuf::uint32 Camera::serialnumber() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Camera.serialNumber)
  return serialnumber_;
}
void Camera::set_serialnumber(::google::protobuf::uint32 value) {
  
  serialnumber_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Camera.serialNumber)
}

// uint32 delta_x = 3;
void Camera::clear_delta_x() {
  delta_x_ = 0u;
}
::google::protobuf::uint32 Camera::delta_x() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Camera.delta_x)
  return delta_x_;
}
void Camera::set_delta_x(::google::protobuf::uint32 value) {
  
  delta_x_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Camera.delta_x)
}

// uint32 delta_y = 4;
void Camera::clear_delta_y() {
  delta_y_ = 0u;
}
::google::protobuf::uint32 Camera::delta_y() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Camera.delta_y)
  return delta_y_;
}
void Camera::set_delta_y(::google::protobuf::uint32 value) {
  
  delta_y_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Camera.delta_y)
}

// uint32 delta_z = 5;
void Camera::clear_delta_z() {
  delta_z_ = 0u;
}
::google::protobuf::uint32 Camera::delta_z() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Camera.delta_z)
  return delta_z_;
}
void Camera::set_delta_z(::google::protobuf::uint32 value) {
  
  delta_z_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Camera.delta_z)
}

// uint32 delta_vx = 6;
void Camera::clear_delta_vx() {
  delta_vx_ = 0u;
}
::google::protobuf::uint32 Camera::delta_vx() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Camera.delta_vx)
  return delta_vx_;
}
void Camera::set_delta_vx(::google::protobuf::uint32 value) {
  
  delta_vx_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Camera.delta_vx)
}

// uint32 delta_vy = 7;
void Camera::clear_delta_vy() {
  delta_vy_ = 0u;
}
::google::protobuf::uint32 Camera::delta_vy() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Camera.delta_vy)
  return delta_vy_;
}
void Camera::set_delta_vy(::google::protobuf::uint32 value) {
  
  delta_vy_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Camera.delta_vy)
}

// uint32 delta_vz = 8;
void Camera::clear_delta_vz() {
  delta_vz_ = 0u;
}
::google::protobuf::uint32 Camera::delta_vz() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Camera.delta_vz)
  return delta_vz_;
}
void Camera::set_delta_vz(::google::protobuf::uint32 value) {
  
  delta_vz_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Camera.delta_vz)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Image::kSerialNumberFieldNumber;
const int Image::kStatusFieldNumber;
const int Image::kSizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Image::Image()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:StreamingFormat.Image)
}
Image::Image(const Image& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&serialnumber_, &from.serialnumber_,
    reinterpret_cast<char*>(&size_) -
    reinterpret_cast<char*>(&serialnumber_) + sizeof(size_));
  // @@protoc_insertion_point(copy_constructor:StreamingFormat.Image)
}

void Image::SharedCtor() {
  ::memset(&serialnumber_, 0, reinterpret_cast<char*>(&size_) -
    reinterpret_cast<char*>(&serialnumber_) + sizeof(size_));
  _cached_size_ = 0;
}

Image::~Image() {
  // @@protoc_insertion_point(destructor:StreamingFormat.Image)
  SharedDtor();
}

void Image::SharedDtor() {
}

void Image::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Image::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[3].descriptor;
}

const Image& Image::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

Image* Image::New(::google::protobuf::Arena* arena) const {
  Image* n = new Image;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Image::Clear() {
// @@protoc_insertion_point(message_clear_start:StreamingFormat.Image)
  ::memset(&serialnumber_, 0, reinterpret_cast<char*>(&size_) -
    reinterpret_cast<char*>(&serialnumber_) + sizeof(size_));
}

bool Image::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StreamingFormat.Image)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 serialNumber = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &serialnumber_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 status = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 size = 4;
      case 4: {
        if (tag == 32u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:StreamingFormat.Image)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StreamingFormat.Image)
  return false;
#undef DO_
}

void Image::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StreamingFormat.Image)
  // uint32 serialNumber = 2;
  if (this->serialnumber() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->serialnumber(), output);
  }

  // uint32 status = 3;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->status(), output);
  }

  // uint32 size = 4;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->size(), output);
  }

  // @@protoc_insertion_point(serialize_end:StreamingFormat.Image)
}

::google::protobuf::uint8* Image::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:StreamingFormat.Image)
  // uint32 serialNumber = 2;
  if (this->serialnumber() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->serialnumber(), target);
  }

  // uint32 status = 3;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->status(), target);
  }

  // uint32 size = 4;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->size(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:StreamingFormat.Image)
  return target;
}

size_t Image::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StreamingFormat.Image)
  size_t total_size = 0;

  // uint32 serialNumber = 2;
  if (this->serialnumber() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->serialnumber());
  }

  // uint32 status = 3;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->status());
  }

  // uint32 size = 4;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->size());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Image::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:StreamingFormat.Image)
  GOOGLE_DCHECK_NE(&from, this);
  const Image* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Image>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:StreamingFormat.Image)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:StreamingFormat.Image)
    MergeFrom(*source);
  }
}

void Image::MergeFrom(const Image& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:StreamingFormat.Image)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.serialnumber() != 0) {
    set_serialnumber(from.serialnumber());
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
  if (from.size() != 0) {
    set_size(from.size());
  }
}

void Image::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:StreamingFormat.Image)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Image::CopyFrom(const Image& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StreamingFormat.Image)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Image::IsInitialized() const {
  return true;
}

void Image::Swap(Image* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Image::InternalSwap(Image* other) {
  std::swap(serialnumber_, other->serialnumber_);
  std::swap(status_, other->status_);
  std::swap(size_, other->size_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Image::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[3];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Image

// uint32 serialNumber = 2;
void Image::clear_serialnumber() {
  serialnumber_ = 0u;
}
::google::protobuf::uint32 Image::serialnumber() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Image.serialNumber)
  return serialnumber_;
}
void Image::set_serialnumber(::google::protobuf::uint32 value) {
  
  serialnumber_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Image.serialNumber)
}

// uint32 status = 3;
void Image::clear_status() {
  status_ = 0u;
}
::google::protobuf::uint32 Image::status() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Image.status)
  return status_;
}
void Image::set_status(::google::protobuf::uint32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Image.status)
}

// uint32 size = 4;
void Image::clear_size() {
  size_ = 0u;
}
::google::protobuf::uint32 Image::size() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.Image.size)
  return size_;
}
void Image::set_size(::google::protobuf::uint32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.Image.size)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Ending::Ending()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:StreamingFormat.Ending)
}
Ending::Ending(const Ending& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:StreamingFormat.Ending)
}

void Ending::SharedCtor() {
  _cached_size_ = 0;
}

Ending::~Ending() {
  // @@protoc_insertion_point(destructor:StreamingFormat.Ending)
  SharedDtor();
}

void Ending::SharedDtor() {
}

void Ending::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Ending::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[4].descriptor;
}

const Ending& Ending::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

Ending* Ending::New(::google::protobuf::Arena* arena) const {
  Ending* n = new Ending;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Ending::Clear() {
// @@protoc_insertion_point(message_clear_start:StreamingFormat.Ending)
}

bool Ending::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StreamingFormat.Ending)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:StreamingFormat.Ending)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StreamingFormat.Ending)
  return false;
#undef DO_
}

void Ending::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StreamingFormat.Ending)
  // @@protoc_insertion_point(serialize_end:StreamingFormat.Ending)
}

::google::protobuf::uint8* Ending::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:StreamingFormat.Ending)
  // @@protoc_insertion_point(serialize_to_array_end:StreamingFormat.Ending)
  return target;
}

size_t Ending::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StreamingFormat.Ending)
  size_t total_size = 0;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Ending::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:StreamingFormat.Ending)
  GOOGLE_DCHECK_NE(&from, this);
  const Ending* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Ending>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:StreamingFormat.Ending)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:StreamingFormat.Ending)
    MergeFrom(*source);
  }
}

void Ending::MergeFrom(const Ending& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:StreamingFormat.Ending)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
}

void Ending::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:StreamingFormat.Ending)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Ending::CopyFrom(const Ending& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StreamingFormat.Ending)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ending::IsInitialized() const {
  return true;
}

void Ending::Swap(Ending* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Ending::InternalSwap(Ending* other) {
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Ending::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[4];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Ending

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StreamingMessage::kTypeFieldNumber;
const int StreamingMessage::kInitMsgFieldNumber;
const int StreamingMessage::kDefaultPosMsgFieldNumber;
const int StreamingMessage::kCameraMsgFieldNumber;
const int StreamingMessage::kImageMsgFieldNumber;
const int StreamingMessage::kEndingMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StreamingMessage::StreamingMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_message_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:StreamingFormat.StreamingMessage)
}
StreamingMessage::StreamingMessage(const StreamingMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_initmsg()) {
    initmsg_ = new ::StreamingFormat::Init(*from.initmsg_);
  } else {
    initmsg_ = NULL;
  }
  if (from.has_defaultposmsg()) {
    defaultposmsg_ = new ::StreamingFormat::DefaultPos(*from.defaultposmsg_);
  } else {
    defaultposmsg_ = NULL;
  }
  if (from.has_cameramsg()) {
    cameramsg_ = new ::StreamingFormat::Camera(*from.cameramsg_);
  } else {
    cameramsg_ = NULL;
  }
  if (from.has_imagemsg()) {
    imagemsg_ = new ::StreamingFormat::Image(*from.imagemsg_);
  } else {
    imagemsg_ = NULL;
  }
  if (from.has_endingmsg()) {
    endingmsg_ = new ::StreamingFormat::Ending(*from.endingmsg_);
  } else {
    endingmsg_ = NULL;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:StreamingFormat.StreamingMessage)
}

void StreamingMessage::SharedCtor() {
  ::memset(&initmsg_, 0, reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&initmsg_) + sizeof(type_));
  _cached_size_ = 0;
}

StreamingMessage::~StreamingMessage() {
  // @@protoc_insertion_point(destructor:StreamingFormat.StreamingMessage)
  SharedDtor();
}

void StreamingMessage::SharedDtor() {
  if (this != internal_default_instance()) {
    delete initmsg_;
  }
  if (this != internal_default_instance()) {
    delete defaultposmsg_;
  }
  if (this != internal_default_instance()) {
    delete cameramsg_;
  }
  if (this != internal_default_instance()) {
    delete imagemsg_;
  }
  if (this != internal_default_instance()) {
    delete endingmsg_;
  }
}

void StreamingMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StreamingMessage::descriptor() {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[5].descriptor;
}

const StreamingMessage& StreamingMessage::default_instance() {
  protobuf_message_2eproto::InitDefaults();
  return *internal_default_instance();
}

StreamingMessage* StreamingMessage::New(::google::protobuf::Arena* arena) const {
  StreamingMessage* n = new StreamingMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StreamingMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:StreamingFormat.StreamingMessage)
  if (GetArenaNoVirtual() == NULL && initmsg_ != NULL) {
    delete initmsg_;
  }
  initmsg_ = NULL;
  if (GetArenaNoVirtual() == NULL && defaultposmsg_ != NULL) {
    delete defaultposmsg_;
  }
  defaultposmsg_ = NULL;
  if (GetArenaNoVirtual() == NULL && cameramsg_ != NULL) {
    delete cameramsg_;
  }
  cameramsg_ = NULL;
  if (GetArenaNoVirtual() == NULL && imagemsg_ != NULL) {
    delete imagemsg_;
  }
  imagemsg_ = NULL;
  if (GetArenaNoVirtual() == NULL && endingmsg_ != NULL) {
    delete endingmsg_;
  }
  endingmsg_ = NULL;
  type_ = 0;
}

bool StreamingMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StreamingFormat.StreamingMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .StreamingFormat.MessageType type = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::StreamingFormat::MessageType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .StreamingFormat.Init initMsg = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_initmsg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .StreamingFormat.DefaultPos defaultPosMsg = 3;
      case 3: {
        if (tag == 26u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_defaultposmsg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .StreamingFormat.Camera cameraMsg = 4;
      case 4: {
        if (tag == 34u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_cameramsg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .StreamingFormat.Image imageMsg = 5;
      case 5: {
        if (tag == 42u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_imagemsg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .StreamingFormat.Ending endingMsg = 6;
      case 6: {
        if (tag == 50u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_endingmsg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:StreamingFormat.StreamingMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StreamingFormat.StreamingMessage)
  return false;
#undef DO_
}

void StreamingMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StreamingFormat.StreamingMessage)
  // .StreamingFormat.MessageType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // .StreamingFormat.Init initMsg = 2;
  if (this->has_initmsg()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->initmsg_, output);
  }

  // .StreamingFormat.DefaultPos defaultPosMsg = 3;
  if (this->has_defaultposmsg()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->defaultposmsg_, output);
  }

  // .StreamingFormat.Camera cameraMsg = 4;
  if (this->has_cameramsg()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->cameramsg_, output);
  }

  // .StreamingFormat.Image imageMsg = 5;
  if (this->has_imagemsg()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->imagemsg_, output);
  }

  // .StreamingFormat.Ending endingMsg = 6;
  if (this->has_endingmsg()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->endingmsg_, output);
  }

  // @@protoc_insertion_point(serialize_end:StreamingFormat.StreamingMessage)
}

::google::protobuf::uint8* StreamingMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:StreamingFormat.StreamingMessage)
  // .StreamingFormat.MessageType type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // .StreamingFormat.Init initMsg = 2;
  if (this->has_initmsg()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->initmsg_, false, target);
  }

  // .StreamingFormat.DefaultPos defaultPosMsg = 3;
  if (this->has_defaultposmsg()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->defaultposmsg_, false, target);
  }

  // .StreamingFormat.Camera cameraMsg = 4;
  if (this->has_cameramsg()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->cameramsg_, false, target);
  }

  // .StreamingFormat.Image imageMsg = 5;
  if (this->has_imagemsg()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->imagemsg_, false, target);
  }

  // .StreamingFormat.Ending endingMsg = 6;
  if (this->has_endingmsg()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        6, *this->endingmsg_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:StreamingFormat.StreamingMessage)
  return target;
}

size_t StreamingMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StreamingFormat.StreamingMessage)
  size_t total_size = 0;

  // .StreamingFormat.Init initMsg = 2;
  if (this->has_initmsg()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->initmsg_);
  }

  // .StreamingFormat.DefaultPos defaultPosMsg = 3;
  if (this->has_defaultposmsg()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->defaultposmsg_);
  }

  // .StreamingFormat.Camera cameraMsg = 4;
  if (this->has_cameramsg()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->cameramsg_);
  }

  // .StreamingFormat.Image imageMsg = 5;
  if (this->has_imagemsg()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->imagemsg_);
  }

  // .StreamingFormat.Ending endingMsg = 6;
  if (this->has_endingmsg()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->endingmsg_);
  }

  // .StreamingFormat.MessageType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StreamingMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:StreamingFormat.StreamingMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const StreamingMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StreamingMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:StreamingFormat.StreamingMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:StreamingFormat.StreamingMessage)
    MergeFrom(*source);
  }
}

void StreamingMessage::MergeFrom(const StreamingMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:StreamingFormat.StreamingMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_initmsg()) {
    mutable_initmsg()->::StreamingFormat::Init::MergeFrom(from.initmsg());
  }
  if (from.has_defaultposmsg()) {
    mutable_defaultposmsg()->::StreamingFormat::DefaultPos::MergeFrom(from.defaultposmsg());
  }
  if (from.has_cameramsg()) {
    mutable_cameramsg()->::StreamingFormat::Camera::MergeFrom(from.cameramsg());
  }
  if (from.has_imagemsg()) {
    mutable_imagemsg()->::StreamingFormat::Image::MergeFrom(from.imagemsg());
  }
  if (from.has_endingmsg()) {
    mutable_endingmsg()->::StreamingFormat::Ending::MergeFrom(from.endingmsg());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void StreamingMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:StreamingFormat.StreamingMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StreamingMessage::CopyFrom(const StreamingMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StreamingFormat.StreamingMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamingMessage::IsInitialized() const {
  return true;
}

void StreamingMessage::Swap(StreamingMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StreamingMessage::InternalSwap(StreamingMessage* other) {
  std::swap(initmsg_, other->initmsg_);
  std::swap(defaultposmsg_, other->defaultposmsg_);
  std::swap(cameramsg_, other->cameramsg_);
  std::swap(imagemsg_, other->imagemsg_);
  std::swap(endingmsg_, other->endingmsg_);
  std::swap(type_, other->type_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StreamingMessage::GetMetadata() const {
  protobuf_message_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_message_2eproto::file_level_metadata[5];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StreamingMessage

// .StreamingFormat.MessageType type = 1;
void StreamingMessage::clear_type() {
  type_ = 0;
}
::StreamingFormat::MessageType StreamingMessage::type() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.StreamingMessage.type)
  return static_cast< ::StreamingFormat::MessageType >(type_);
}
void StreamingMessage::set_type(::StreamingFormat::MessageType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:StreamingFormat.StreamingMessage.type)
}

// .StreamingFormat.Init initMsg = 2;
bool StreamingMessage::has_initmsg() const {
  return this != internal_default_instance() && initmsg_ != NULL;
}
void StreamingMessage::clear_initmsg() {
  if (GetArenaNoVirtual() == NULL && initmsg_ != NULL) delete initmsg_;
  initmsg_ = NULL;
}
const ::StreamingFormat::Init& StreamingMessage::initmsg() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.StreamingMessage.initMsg)
  return initmsg_ != NULL ? *initmsg_
                         : *::StreamingFormat::Init::internal_default_instance();
}
::StreamingFormat::Init* StreamingMessage::mutable_initmsg() {
  
  if (initmsg_ == NULL) {
    initmsg_ = new ::StreamingFormat::Init;
  }
  // @@protoc_insertion_point(field_mutable:StreamingFormat.StreamingMessage.initMsg)
  return initmsg_;
}
::StreamingFormat::Init* StreamingMessage::release_initmsg() {
  // @@protoc_insertion_point(field_release:StreamingFormat.StreamingMessage.initMsg)
  
  ::StreamingFormat::Init* temp = initmsg_;
  initmsg_ = NULL;
  return temp;
}
void StreamingMessage::set_allocated_initmsg(::StreamingFormat::Init* initmsg) {
  delete initmsg_;
  initmsg_ = initmsg;
  if (initmsg) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StreamingFormat.StreamingMessage.initMsg)
}

// .StreamingFormat.DefaultPos defaultPosMsg = 3;
bool StreamingMessage::has_defaultposmsg() const {
  return this != internal_default_instance() && defaultposmsg_ != NULL;
}
void StreamingMessage::clear_defaultposmsg() {
  if (GetArenaNoVirtual() == NULL && defaultposmsg_ != NULL) delete defaultposmsg_;
  defaultposmsg_ = NULL;
}
const ::StreamingFormat::DefaultPos& StreamingMessage::defaultposmsg() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.StreamingMessage.defaultPosMsg)
  return defaultposmsg_ != NULL ? *defaultposmsg_
                         : *::StreamingFormat::DefaultPos::internal_default_instance();
}
::StreamingFormat::DefaultPos* StreamingMessage::mutable_defaultposmsg() {
  
  if (defaultposmsg_ == NULL) {
    defaultposmsg_ = new ::StreamingFormat::DefaultPos;
  }
  // @@protoc_insertion_point(field_mutable:StreamingFormat.StreamingMessage.defaultPosMsg)
  return defaultposmsg_;
}
::StreamingFormat::DefaultPos* StreamingMessage::release_defaultposmsg() {
  // @@protoc_insertion_point(field_release:StreamingFormat.StreamingMessage.defaultPosMsg)
  
  ::StreamingFormat::DefaultPos* temp = defaultposmsg_;
  defaultposmsg_ = NULL;
  return temp;
}
void StreamingMessage::set_allocated_defaultposmsg(::StreamingFormat::DefaultPos* defaultposmsg) {
  delete defaultposmsg_;
  defaultposmsg_ = defaultposmsg;
  if (defaultposmsg) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StreamingFormat.StreamingMessage.defaultPosMsg)
}

// .StreamingFormat.Camera cameraMsg = 4;
bool StreamingMessage::has_cameramsg() const {
  return this != internal_default_instance() && cameramsg_ != NULL;
}
void StreamingMessage::clear_cameramsg() {
  if (GetArenaNoVirtual() == NULL && cameramsg_ != NULL) delete cameramsg_;
  cameramsg_ = NULL;
}
const ::StreamingFormat::Camera& StreamingMessage::cameramsg() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.StreamingMessage.cameraMsg)
  return cameramsg_ != NULL ? *cameramsg_
                         : *::StreamingFormat::Camera::internal_default_instance();
}
::StreamingFormat::Camera* StreamingMessage::mutable_cameramsg() {
  
  if (cameramsg_ == NULL) {
    cameramsg_ = new ::StreamingFormat::Camera;
  }
  // @@protoc_insertion_point(field_mutable:StreamingFormat.StreamingMessage.cameraMsg)
  return cameramsg_;
}
::StreamingFormat::Camera* StreamingMessage::release_cameramsg() {
  // @@protoc_insertion_point(field_release:StreamingFormat.StreamingMessage.cameraMsg)
  
  ::StreamingFormat::Camera* temp = cameramsg_;
  cameramsg_ = NULL;
  return temp;
}
void StreamingMessage::set_allocated_cameramsg(::StreamingFormat::Camera* cameramsg) {
  delete cameramsg_;
  cameramsg_ = cameramsg;
  if (cameramsg) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StreamingFormat.StreamingMessage.cameraMsg)
}

// .StreamingFormat.Image imageMsg = 5;
bool StreamingMessage::has_imagemsg() const {
  return this != internal_default_instance() && imagemsg_ != NULL;
}
void StreamingMessage::clear_imagemsg() {
  if (GetArenaNoVirtual() == NULL && imagemsg_ != NULL) delete imagemsg_;
  imagemsg_ = NULL;
}
const ::StreamingFormat::Image& StreamingMessage::imagemsg() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.StreamingMessage.imageMsg)
  return imagemsg_ != NULL ? *imagemsg_
                         : *::StreamingFormat::Image::internal_default_instance();
}
::StreamingFormat::Image* StreamingMessage::mutable_imagemsg() {
  
  if (imagemsg_ == NULL) {
    imagemsg_ = new ::StreamingFormat::Image;
  }
  // @@protoc_insertion_point(field_mutable:StreamingFormat.StreamingMessage.imageMsg)
  return imagemsg_;
}
::StreamingFormat::Image* StreamingMessage::release_imagemsg() {
  // @@protoc_insertion_point(field_release:StreamingFormat.StreamingMessage.imageMsg)
  
  ::StreamingFormat::Image* temp = imagemsg_;
  imagemsg_ = NULL;
  return temp;
}
void StreamingMessage::set_allocated_imagemsg(::StreamingFormat::Image* imagemsg) {
  delete imagemsg_;
  imagemsg_ = imagemsg;
  if (imagemsg) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StreamingFormat.StreamingMessage.imageMsg)
}

// .StreamingFormat.Ending endingMsg = 6;
bool StreamingMessage::has_endingmsg() const {
  return this != internal_default_instance() && endingmsg_ != NULL;
}
void StreamingMessage::clear_endingmsg() {
  if (GetArenaNoVirtual() == NULL && endingmsg_ != NULL) delete endingmsg_;
  endingmsg_ = NULL;
}
const ::StreamingFormat::Ending& StreamingMessage::endingmsg() const {
  // @@protoc_insertion_point(field_get:StreamingFormat.StreamingMessage.endingMsg)
  return endingmsg_ != NULL ? *endingmsg_
                         : *::StreamingFormat::Ending::internal_default_instance();
}
::StreamingFormat::Ending* StreamingMessage::mutable_endingmsg() {
  
  if (endingmsg_ == NULL) {
    endingmsg_ = new ::StreamingFormat::Ending;
  }
  // @@protoc_insertion_point(field_mutable:StreamingFormat.StreamingMessage.endingMsg)
  return endingmsg_;
}
::StreamingFormat::Ending* StreamingMessage::release_endingmsg() {
  // @@protoc_insertion_point(field_release:StreamingFormat.StreamingMessage.endingMsg)
  
  ::StreamingFormat::Ending* temp = endingmsg_;
  endingmsg_ = NULL;
  return temp;
}
void StreamingMessage::set_allocated_endingmsg(::StreamingFormat::Ending* endingmsg) {
  delete endingmsg_;
  endingmsg_ = endingmsg;
  if (endingmsg) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StreamingFormat.StreamingMessage.endingMsg)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace StreamingFormat

// @@protoc_insertion_point(global_scope)
