// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

#ifndef PROTOBUF_packet_2eproto__INCLUDED
#define PROTOBUF_packet_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace packet {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_packet_2eproto();
void protobuf_AssignDesc_packet_2eproto();
void protobuf_ShutdownFile_packet_2eproto();

class CameraPacket;
class DefaultPosPacket;
class EndingPacket;
class ImagePacket;
class InItPacket;

enum PacketType {
  PkktInit = 0,
  PktDefaultPos = 1,
  PktCameraInfo = 2,
  PktImage = 3,
  PktEnding = 4,
  PacketType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PacketType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PacketType_IsValid(int value);
const PacketType PacketType_MIN = PkktInit;
const PacketType PacketType_MAX = PktEnding;
const int PacketType_ARRAYSIZE = PacketType_MAX + 1;

const ::google::protobuf::EnumDescriptor* PacketType_descriptor();
inline const ::std::string& PacketType_Name(PacketType value) {
  return ::google::protobuf::internal::NameOfEnum(
    PacketType_descriptor(), value);
}
inline bool PacketType_Parse(
    const ::std::string& name, PacketType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PacketType>(
    PacketType_descriptor(), name, value);
}
// ===================================================================

class InItPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packet.InItPacket) */ {
 public:
  InItPacket();
  virtual ~InItPacket();

  InItPacket(const InItPacket& from);

  inline InItPacket& operator=(const InItPacket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InItPacket& default_instance();

  void Swap(InItPacket* other);

  // implements Message ----------------------------------------------

  inline InItPacket* New() const { return New(NULL); }

  InItPacket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InItPacket& from);
  void MergeFrom(const InItPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(InItPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packet.PacketType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::packet::PacketType type() const;
  void set_type(::packet::PacketType value);

  // optional uint32 width = 2;
  void clear_width();
  static const int kWidthFieldNumber = 2;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // optional uint32 hight = 3;
  void clear_hight();
  static const int kHightFieldNumber = 3;
  ::google::protobuf::uint32 hight() const;
  void set_hight(::google::protobuf::uint32 value);

  // optional uint32 moduleID = 4;
  void clear_moduleid();
  static const int kModuleIDFieldNumber = 4;
  ::google::protobuf::uint32 moduleid() const;
  void set_moduleid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:packet.InItPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int type_;
  ::google::protobuf::uint32 width_;
  ::google::protobuf::uint32 hight_;
  ::google::protobuf::uint32 moduleid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_packet_2eproto();
  friend void protobuf_AssignDesc_packet_2eproto();
  friend void protobuf_ShutdownFile_packet_2eproto();

  void InitAsDefaultInstance();
  static InItPacket* default_instance_;
};
// -------------------------------------------------------------------

class DefaultPosPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packet.DefaultPosPacket) */ {
 public:
  DefaultPosPacket();
  virtual ~DefaultPosPacket();

  DefaultPosPacket(const DefaultPosPacket& from);

  inline DefaultPosPacket& operator=(const DefaultPosPacket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DefaultPosPacket& default_instance();

  void Swap(DefaultPosPacket* other);

  // implements Message ----------------------------------------------

  inline DefaultPosPacket* New() const { return New(NULL); }

  DefaultPosPacket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DefaultPosPacket& from);
  void MergeFrom(const DefaultPosPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DefaultPosPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packet.PacketType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::packet::PacketType type() const;
  void set_type(::packet::PacketType value);

  // optional uint32 x = 2;
  void clear_x();
  static const int kXFieldNumber = 2;
  ::google::protobuf::uint32 x() const;
  void set_x(::google::protobuf::uint32 value);

  // optional uint32 y = 3;
  void clear_y();
  static const int kYFieldNumber = 3;
  ::google::protobuf::uint32 y() const;
  void set_y(::google::protobuf::uint32 value);

  // optional uint32 z = 4;
  void clear_z();
  static const int kZFieldNumber = 4;
  ::google::protobuf::uint32 z() const;
  void set_z(::google::protobuf::uint32 value);

  // optional uint32 vx = 5;
  void clear_vx();
  static const int kVxFieldNumber = 5;
  ::google::protobuf::uint32 vx() const;
  void set_vx(::google::protobuf::uint32 value);

  // optional uint32 vy = 6;
  void clear_vy();
  static const int kVyFieldNumber = 6;
  ::google::protobuf::uint32 vy() const;
  void set_vy(::google::protobuf::uint32 value);

  // optional uint32 vz = 7;
  void clear_vz();
  static const int kVzFieldNumber = 7;
  ::google::protobuf::uint32 vz() const;
  void set_vz(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:packet.DefaultPosPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int type_;
  ::google::protobuf::uint32 x_;
  ::google::protobuf::uint32 y_;
  ::google::protobuf::uint32 z_;
  ::google::protobuf::uint32 vx_;
  ::google::protobuf::uint32 vy_;
  ::google::protobuf::uint32 vz_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_packet_2eproto();
  friend void protobuf_AssignDesc_packet_2eproto();
  friend void protobuf_ShutdownFile_packet_2eproto();

  void InitAsDefaultInstance();
  static DefaultPosPacket* default_instance_;
};
// -------------------------------------------------------------------

class CameraPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packet.CameraPacket) */ {
 public:
  CameraPacket();
  virtual ~CameraPacket();

  CameraPacket(const CameraPacket& from);

  inline CameraPacket& operator=(const CameraPacket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CameraPacket& default_instance();

  void Swap(CameraPacket* other);

  // implements Message ----------------------------------------------

  inline CameraPacket* New() const { return New(NULL); }

  CameraPacket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CameraPacket& from);
  void MergeFrom(const CameraPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CameraPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packet.PacketType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::packet::PacketType type() const;
  void set_type(::packet::PacketType value);

  // optional uint32 serialNumber = 2;
  void clear_serialnumber();
  static const int kSerialNumberFieldNumber = 2;
  ::google::protobuf::uint32 serialnumber() const;
  void set_serialnumber(::google::protobuf::uint32 value);

  // optional uint32 delta_x = 3;
  void clear_delta_x();
  static const int kDeltaXFieldNumber = 3;
  ::google::protobuf::uint32 delta_x() const;
  void set_delta_x(::google::protobuf::uint32 value);

  // optional uint32 delta_y = 4;
  void clear_delta_y();
  static const int kDeltaYFieldNumber = 4;
  ::google::protobuf::uint32 delta_y() const;
  void set_delta_y(::google::protobuf::uint32 value);

  // optional uint32 delta_z = 5;
  void clear_delta_z();
  static const int kDeltaZFieldNumber = 5;
  ::google::protobuf::uint32 delta_z() const;
  void set_delta_z(::google::protobuf::uint32 value);

  // optional uint32 delta_vx = 6;
  void clear_delta_vx();
  static const int kDeltaVxFieldNumber = 6;
  ::google::protobuf::uint32 delta_vx() const;
  void set_delta_vx(::google::protobuf::uint32 value);

  // optional uint32 delta_vy = 7;
  void clear_delta_vy();
  static const int kDeltaVyFieldNumber = 7;
  ::google::protobuf::uint32 delta_vy() const;
  void set_delta_vy(::google::protobuf::uint32 value);

  // optional uint32 delta_vz = 8;
  void clear_delta_vz();
  static const int kDeltaVzFieldNumber = 8;
  ::google::protobuf::uint32 delta_vz() const;
  void set_delta_vz(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:packet.CameraPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int type_;
  ::google::protobuf::uint32 serialnumber_;
  ::google::protobuf::uint32 delta_x_;
  ::google::protobuf::uint32 delta_y_;
  ::google::protobuf::uint32 delta_z_;
  ::google::protobuf::uint32 delta_vx_;
  ::google::protobuf::uint32 delta_vy_;
  ::google::protobuf::uint32 delta_vz_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_packet_2eproto();
  friend void protobuf_AssignDesc_packet_2eproto();
  friend void protobuf_ShutdownFile_packet_2eproto();

  void InitAsDefaultInstance();
  static CameraPacket* default_instance_;
};
// -------------------------------------------------------------------

class ImagePacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packet.ImagePacket) */ {
 public:
  ImagePacket();
  virtual ~ImagePacket();

  ImagePacket(const ImagePacket& from);

  inline ImagePacket& operator=(const ImagePacket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ImagePacket& default_instance();

  void Swap(ImagePacket* other);

  // implements Message ----------------------------------------------

  inline ImagePacket* New() const { return New(NULL); }

  ImagePacket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ImagePacket& from);
  void MergeFrom(const ImagePacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ImagePacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packet.PacketType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::packet::PacketType type() const;
  void set_type(::packet::PacketType value);

  // optional uint32 serialNumber = 2;
  void clear_serialnumber();
  static const int kSerialNumberFieldNumber = 2;
  ::google::protobuf::uint32 serialnumber() const;
  void set_serialnumber(::google::protobuf::uint32 value);

  // optional uint32 status = 3;
  void clear_status();
  static const int kStatusFieldNumber = 3;
  ::google::protobuf::uint32 status() const;
  void set_status(::google::protobuf::uint32 value);

  // optional uint32 size = 4;
  void clear_size();
  static const int kSizeFieldNumber = 4;
  ::google::protobuf::uint32 size() const;
  void set_size(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:packet.ImagePacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int type_;
  ::google::protobuf::uint32 serialnumber_;
  ::google::protobuf::uint32 status_;
  ::google::protobuf::uint32 size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_packet_2eproto();
  friend void protobuf_AssignDesc_packet_2eproto();
  friend void protobuf_ShutdownFile_packet_2eproto();

  void InitAsDefaultInstance();
  static ImagePacket* default_instance_;
};
// -------------------------------------------------------------------

class EndingPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packet.EndingPacket) */ {
 public:
  EndingPacket();
  virtual ~EndingPacket();

  EndingPacket(const EndingPacket& from);

  inline EndingPacket& operator=(const EndingPacket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EndingPacket& default_instance();

  void Swap(EndingPacket* other);

  // implements Message ----------------------------------------------

  inline EndingPacket* New() const { return New(NULL); }

  EndingPacket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EndingPacket& from);
  void MergeFrom(const EndingPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EndingPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packet.PacketType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::packet::PacketType type() const;
  void set_type(::packet::PacketType value);

  // @@protoc_insertion_point(class_scope:packet.EndingPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_packet_2eproto();
  friend void protobuf_AssignDesc_packet_2eproto();
  friend void protobuf_ShutdownFile_packet_2eproto();

  void InitAsDefaultInstance();
  static EndingPacket* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// InItPacket

// optional .packet.PacketType type = 1;
inline void InItPacket::clear_type() {
  type_ = 0;
}
inline ::packet::PacketType InItPacket::type() const {
  // @@protoc_insertion_point(field_get:packet.InItPacket.type)
  return static_cast< ::packet::PacketType >(type_);
}
inline void InItPacket::set_type(::packet::PacketType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:packet.InItPacket.type)
}

// optional uint32 width = 2;
inline void InItPacket::clear_width() {
  width_ = 0u;
}
inline ::google::protobuf::uint32 InItPacket::width() const {
  // @@protoc_insertion_point(field_get:packet.InItPacket.width)
  return width_;
}
inline void InItPacket::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:packet.InItPacket.width)
}

// optional uint32 hight = 3;
inline void InItPacket::clear_hight() {
  hight_ = 0u;
}
inline ::google::protobuf::uint32 InItPacket::hight() const {
  // @@protoc_insertion_point(field_get:packet.InItPacket.hight)
  return hight_;
}
inline void InItPacket::set_hight(::google::protobuf::uint32 value) {
  
  hight_ = value;
  // @@protoc_insertion_point(field_set:packet.InItPacket.hight)
}

// optional uint32 moduleID = 4;
inline void InItPacket::clear_moduleid() {
  moduleid_ = 0u;
}
inline ::google::protobuf::uint32 InItPacket::moduleid() const {
  // @@protoc_insertion_point(field_get:packet.InItPacket.moduleID)
  return moduleid_;
}
inline void InItPacket::set_moduleid(::google::protobuf::uint32 value) {
  
  moduleid_ = value;
  // @@protoc_insertion_point(field_set:packet.InItPacket.moduleID)
}

// -------------------------------------------------------------------

// DefaultPosPacket

// optional .packet.PacketType type = 1;
inline void DefaultPosPacket::clear_type() {
  type_ = 0;
}
inline ::packet::PacketType DefaultPosPacket::type() const {
  // @@protoc_insertion_point(field_get:packet.DefaultPosPacket.type)
  return static_cast< ::packet::PacketType >(type_);
}
inline void DefaultPosPacket::set_type(::packet::PacketType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:packet.DefaultPosPacket.type)
}

// optional uint32 x = 2;
inline void DefaultPosPacket::clear_x() {
  x_ = 0u;
}
inline ::google::protobuf::uint32 DefaultPosPacket::x() const {
  // @@protoc_insertion_point(field_get:packet.DefaultPosPacket.x)
  return x_;
}
inline void DefaultPosPacket::set_x(::google::protobuf::uint32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:packet.DefaultPosPacket.x)
}

// optional uint32 y = 3;
inline void DefaultPosPacket::clear_y() {
  y_ = 0u;
}
inline ::google::protobuf::uint32 DefaultPosPacket::y() const {
  // @@protoc_insertion_point(field_get:packet.DefaultPosPacket.y)
  return y_;
}
inline void DefaultPosPacket::set_y(::google::protobuf::uint32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:packet.DefaultPosPacket.y)
}

// optional uint32 z = 4;
inline void DefaultPosPacket::clear_z() {
  z_ = 0u;
}
inline ::google::protobuf::uint32 DefaultPosPacket::z() const {
  // @@protoc_insertion_point(field_get:packet.DefaultPosPacket.z)
  return z_;
}
inline void DefaultPosPacket::set_z(::google::protobuf::uint32 value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:packet.DefaultPosPacket.z)
}

// optional uint32 vx = 5;
inline void DefaultPosPacket::clear_vx() {
  vx_ = 0u;
}
inline ::google::protobuf::uint32 DefaultPosPacket::vx() const {
  // @@protoc_insertion_point(field_get:packet.DefaultPosPacket.vx)
  return vx_;
}
inline void DefaultPosPacket::set_vx(::google::protobuf::uint32 value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:packet.DefaultPosPacket.vx)
}

// optional uint32 vy = 6;
inline void DefaultPosPacket::clear_vy() {
  vy_ = 0u;
}
inline ::google::protobuf::uint32 DefaultPosPacket::vy() const {
  // @@protoc_insertion_point(field_get:packet.DefaultPosPacket.vy)
  return vy_;
}
inline void DefaultPosPacket::set_vy(::google::protobuf::uint32 value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:packet.DefaultPosPacket.vy)
}

// optional uint32 vz = 7;
inline void DefaultPosPacket::clear_vz() {
  vz_ = 0u;
}
inline ::google::protobuf::uint32 DefaultPosPacket::vz() const {
  // @@protoc_insertion_point(field_get:packet.DefaultPosPacket.vz)
  return vz_;
}
inline void DefaultPosPacket::set_vz(::google::protobuf::uint32 value) {
  
  vz_ = value;
  // @@protoc_insertion_point(field_set:packet.DefaultPosPacket.vz)
}

// -------------------------------------------------------------------

// CameraPacket

// optional .packet.PacketType type = 1;
inline void CameraPacket::clear_type() {
  type_ = 0;
}
inline ::packet::PacketType CameraPacket::type() const {
  // @@protoc_insertion_point(field_get:packet.CameraPacket.type)
  return static_cast< ::packet::PacketType >(type_);
}
inline void CameraPacket::set_type(::packet::PacketType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:packet.CameraPacket.type)
}

// optional uint32 serialNumber = 2;
inline void CameraPacket::clear_serialnumber() {
  serialnumber_ = 0u;
}
inline ::google::protobuf::uint32 CameraPacket::serialnumber() const {
  // @@protoc_insertion_point(field_get:packet.CameraPacket.serialNumber)
  return serialnumber_;
}
inline void CameraPacket::set_serialnumber(::google::protobuf::uint32 value) {
  
  serialnumber_ = value;
  // @@protoc_insertion_point(field_set:packet.CameraPacket.serialNumber)
}

// optional uint32 delta_x = 3;
inline void CameraPacket::clear_delta_x() {
  delta_x_ = 0u;
}
inline ::google::protobuf::uint32 CameraPacket::delta_x() const {
  // @@protoc_insertion_point(field_get:packet.CameraPacket.delta_x)
  return delta_x_;
}
inline void CameraPacket::set_delta_x(::google::protobuf::uint32 value) {
  
  delta_x_ = value;
  // @@protoc_insertion_point(field_set:packet.CameraPacket.delta_x)
}

// optional uint32 delta_y = 4;
inline void CameraPacket::clear_delta_y() {
  delta_y_ = 0u;
}
inline ::google::protobuf::uint32 CameraPacket::delta_y() const {
  // @@protoc_insertion_point(field_get:packet.CameraPacket.delta_y)
  return delta_y_;
}
inline void CameraPacket::set_delta_y(::google::protobuf::uint32 value) {
  
  delta_y_ = value;
  // @@protoc_insertion_point(field_set:packet.CameraPacket.delta_y)
}

// optional uint32 delta_z = 5;
inline void CameraPacket::clear_delta_z() {
  delta_z_ = 0u;
}
inline ::google::protobuf::uint32 CameraPacket::delta_z() const {
  // @@protoc_insertion_point(field_get:packet.CameraPacket.delta_z)
  return delta_z_;
}
inline void CameraPacket::set_delta_z(::google::protobuf::uint32 value) {
  
  delta_z_ = value;
  // @@protoc_insertion_point(field_set:packet.CameraPacket.delta_z)
}

// optional uint32 delta_vx = 6;
inline void CameraPacket::clear_delta_vx() {
  delta_vx_ = 0u;
}
inline ::google::protobuf::uint32 CameraPacket::delta_vx() const {
  // @@protoc_insertion_point(field_get:packet.CameraPacket.delta_vx)
  return delta_vx_;
}
inline void CameraPacket::set_delta_vx(::google::protobuf::uint32 value) {
  
  delta_vx_ = value;
  // @@protoc_insertion_point(field_set:packet.CameraPacket.delta_vx)
}

// optional uint32 delta_vy = 7;
inline void CameraPacket::clear_delta_vy() {
  delta_vy_ = 0u;
}
inline ::google::protobuf::uint32 CameraPacket::delta_vy() const {
  // @@protoc_insertion_point(field_get:packet.CameraPacket.delta_vy)
  return delta_vy_;
}
inline void CameraPacket::set_delta_vy(::google::protobuf::uint32 value) {
  
  delta_vy_ = value;
  // @@protoc_insertion_point(field_set:packet.CameraPacket.delta_vy)
}

// optional uint32 delta_vz = 8;
inline void CameraPacket::clear_delta_vz() {
  delta_vz_ = 0u;
}
inline ::google::protobuf::uint32 CameraPacket::delta_vz() const {
  // @@protoc_insertion_point(field_get:packet.CameraPacket.delta_vz)
  return delta_vz_;
}
inline void CameraPacket::set_delta_vz(::google::protobuf::uint32 value) {
  
  delta_vz_ = value;
  // @@protoc_insertion_point(field_set:packet.CameraPacket.delta_vz)
}

// -------------------------------------------------------------------

// ImagePacket

// optional .packet.PacketType type = 1;
inline void ImagePacket::clear_type() {
  type_ = 0;
}
inline ::packet::PacketType ImagePacket::type() const {
  // @@protoc_insertion_point(field_get:packet.ImagePacket.type)
  return static_cast< ::packet::PacketType >(type_);
}
inline void ImagePacket::set_type(::packet::PacketType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:packet.ImagePacket.type)
}

// optional uint32 serialNumber = 2;
inline void ImagePacket::clear_serialnumber() {
  serialnumber_ = 0u;
}
inline ::google::protobuf::uint32 ImagePacket::serialnumber() const {
  // @@protoc_insertion_point(field_get:packet.ImagePacket.serialNumber)
  return serialnumber_;
}
inline void ImagePacket::set_serialnumber(::google::protobuf::uint32 value) {
  
  serialnumber_ = value;
  // @@protoc_insertion_point(field_set:packet.ImagePacket.serialNumber)
}

// optional uint32 status = 3;
inline void ImagePacket::clear_status() {
  status_ = 0u;
}
inline ::google::protobuf::uint32 ImagePacket::status() const {
  // @@protoc_insertion_point(field_get:packet.ImagePacket.status)
  return status_;
}
inline void ImagePacket::set_status(::google::protobuf::uint32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:packet.ImagePacket.status)
}

// optional uint32 size = 4;
inline void ImagePacket::clear_size() {
  size_ = 0u;
}
inline ::google::protobuf::uint32 ImagePacket::size() const {
  // @@protoc_insertion_point(field_get:packet.ImagePacket.size)
  return size_;
}
inline void ImagePacket::set_size(::google::protobuf::uint32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:packet.ImagePacket.size)
}

// -------------------------------------------------------------------

// EndingPacket

// optional .packet.PacketType type = 1;
inline void EndingPacket::clear_type() {
  type_ = 0;
}
inline ::packet::PacketType EndingPacket::type() const {
  // @@protoc_insertion_point(field_get:packet.EndingPacket.type)
  return static_cast< ::packet::PacketType >(type_);
}
inline void EndingPacket::set_type(::packet::PacketType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:packet.EndingPacket.type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace packet

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::packet::PacketType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::packet::PacketType>() {
  return ::packet::PacketType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_packet_2eproto__INCLUDED
